# Generated by Django 4.2.4 on 2023-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('domain', models.URLField(default=None, null=True)),
                ('project_name', models.CharField(max_length=256)),
                ('github_url', models.URLField()),
                ('description', models.TextField(default='')),
                ('instance_id', models.CharField(default=None, max_length=48, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
